### ISSUE TITLE
Running dldoc 

### ISSUE THREAD

**Issue by Anirban166** [Anirban166/GSoC21-Tests#9]
I tried to use `dldoc`:
```r
> dldoc("~/R/directlabels/pkg/directlabels")
Error in setwd(pkgdir) : cannot change working directory
```
I checked my working directory:
```r
> getwd()
[1] "/Users/anirban166"
```
Ensured `/Users/anirban166` is `~/` for the sake of internal peace:
```r
> # setwd(getwd())
> setwd("~/")
> dldoc("~/R/directlabels/pkg/directlabels")
Error in setwd(pkgdir) : cannot change working directory
```
Alright, this must mean the packages are stored somewhere else then. Checked library paths:
```r
> .libPaths()
[1] "/usr/local/lib/R/4.0/site-library"         "/usr/local/Cellar/r/4.0.3_2/lib/R/library"
> .Library
[1] "/usr/local/Cellar/r/4.0.3_2/lib/R/library"
``` 
The first value must be it, i.e. `.libPaths()[1]`, so I tried prefixing that path:
```r
> dldoc("/usr/local/lib/R/4.0/site-library/directlabels/pkg/directlabels")
Error in setwd(pkgdir) : cannot change working directory
```
Ensured that the above is the correct library path for `directlabels`:
```r
> find.package("directlabels")
[1] "/usr/local/lib/R/4.0/site-library/directlabels"
```
Removed `/pkg/directlabels` from the path to see if its the correct version:
```r
> dldoc("/usr/local/lib/R/4.0/site-library/directlabels")
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") : cannot open file '.R': No such file or directory
```
Cool, new error

**Comment by Anirban166** [comment]
Hi @tdhock could you please check on this?  

I installed R via Homebrew, so I guess thats why the library paths are like that. If I used the default package install system, the location would probably have been something like `./Library/Frameworks/R.framework//Versions/4.0/Resources/library/directlabels`, but either way I get this error now:
```r
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") : cannot open file '.R': No such file or directory
```

I'm getting this while building the documentation skeleton using `inlinedocs` as well:
```r
> inlinedocs::package.skeleton.dx("/usr/local/lib/R/4.0/site-library/directlabels")
Loading required package: grid
Loading required package: quadprog
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'utility.function.R': No such file or directory
```
Any idea how to resolve this?

**Comment by tdhock** [comment]
"/usr/local/lib/R/4.0/site-library/directlabels" is the installed directory, you need to run these commands on the source directory.

**Comment by tdhock** [comment]
also if you want to get dldoc to work you will need to add back the old directlabels/tests/doc directory which is in svn https://r-forge.r-project.org/scm/viewvc.php/pkg/directlabels/tests/doc/?root=directlabels but not in github (since I never re-generated docs since moving to github)
- would be good to remove old methods that nobody uses any more (contour plots, bad line plot methods)
- would be good to add more informative error messages like "no doc directory found so not generating any documentation"

**Comment by Anirban166** [comment]
> "/usr/local/lib/R/4.0/site-library/directlabels" is the installed directory, you need to run these commands on the source directory.

> also if you want to get dldoc to work you will need to add back the old directlabels/tests/doc directory which is in svn https://r-forge.r-project.org/scm/viewvc.php/pkg/directlabels/tests/doc/?root=directlabels but not in github (since I never re-generated docs since moving to github)

Gotcha! and right, I realized that I needed that directory while going through [dldocs](https://github.com/tdhock/directlabels/blob/54ccbb95e0079649d350865f8c063adfc8fbbf0b/R/doc.R#L4) before, but I wondered where the folder was! 
I added that `/doc` folder within `/tests` and I'm using the source directory now, which should work fine. Currently, I'm trying to sort the dependency issues:
```r
> dldoc("/Users/anirban166/Downloads/directlabels")
Error in find.package(package, lib.loc, verbose = verbose) : 
  there is no package called ‘ElemStatLearn’
> install.packages("ElemStatLearn")
Installing package into ‘/usr/local/lib/R/4.0/site-library’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘ElemStatLearn’ is not available for this version of R
A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
```
After I'm done, I'll re-compute the docs in a 'gh-pages' branch I created a while ago within my forked version: (removed my edits, making it even with your master)
```sh
anirban166$ git checkout -b gh-pages
Switched to a new branch 'gh-pages'
anirban166$ git reset --hard HEAD~4
HEAD is now at 54ccbb9 fix grayscale calc for default white/black text in polygon.method
anirban166$ git push -u origin gh-pages
```
From this branch I further created another one to simply test the website as it is currently with the files from the svn repo: (deleted the files in this branch to avoid overlap)
```
anirban166$ git checkout -b test
Switched to a new branch 'test'
anirban166$ git push -u origin test
```
For getting the svn repo, I went to the link you provided (being new, I did wander around for a bit) and I finally downloaded it from the [source code management section](https://r-forge.r-project.org/scm/?group_id=481). I did get an error initially, which was expected as I didn't install svn: 
```sh
anirban166$ svn checkout svn://svn.r-forge.r-project.org/svnroot/directlabels/
svn: error: The subversion command line tools are no longer provided by Xcode.
```
But apparently, Xcode or OS X's command line tools no longer support svn as well (cannot install with this version), so I had to explicitly install it via Homebrew:
```sh
anirban166$ brew install svn
```
After a long wait (too many homebrew updates!) I finally got the files and I put the website material or contents of `www/` in root and then checked the deployment on Github pages: (hosted via the 'test'-branch) 
https://anirban166.github.io/directlabels/

Since it includes a directory within the old svn repo, the documentation generation part in the readme ([last update](https://github.com/tdhock/directlabels/commit/dbd09f36784fc8f25b216e95c3f11fad98d58d30#diff-ecbc1aa90e9ff97a00b0b2aab1551bceee0c4d21993146bdcb1af4de31c9cac6)) could do with a caveat which includes that point, but yeah there isn't a need to mention that now given that we will be computing the docs from now on, which requires the `/doc` folder in the Git repo too. 

> - would be good to remove old methods that nobody uses any more (contour plots, bad line plot methods)
> - would be good to add more informative error messages like "no doc directory found so not generating any documentation"

I will add them to my proposal 👍 

Also note that we need to change some links. Like [http://directlabels.r-forge.r-project.org/](http://directlabels.r-forge.r-project.org/) mentions will need to be changed to [https://tdhock.github.io/directlabels/](https://tdhock.github.io/directlabels/), for e.g. in the bottom section of `docs/index.html`:
Current version:
```html
<center>
<table>
<tr><td>Please
contact <a href="http://sugiyama-www.cs.titech.ac.jp/~toby/">Toby
Dylan Hocking</a> if you are
using <a href="http://directlabels.r-forge.r-project.org/">directlabels</a>
or have ideas to contribute, thanks!</td>
</tr>
<tr><td align="center">Documentation website generated from source
code version 2014.1.27
(svn revision 675)
using <a href="http://inlinedocs.r-forge.r-project.org">inlinedocs</a>.</td>
</tr>
<tr>
<td align="center">
    <a href="http://validator.w3.org/check?uri=referer">validate</a>
</td>
</tr>
</table>
</center>
```
Possible updated version:
```html
<center>
<table>
<tr><td>Please
contact <a href="http://sugiyama-www.cs.titech.ac.jp/~toby/">Toby
<!-- The link above doesn't work atm, perhaps you would like your current personal website instead: http://tdhock.github.io/ -->
Dylan Hocking</a> if you are
using <a href="https://tdhock.github.io/directlabels/">directlabels</a>
or have ideas to contribute, thanks!</td>
</tr>
<tr><td align="center">Documentation website generated from source
code version 2014.1.27
using <a href="https://github.com/tdhock/inlinedocs">inlinedocs</a>.</td>
<!-- Should be http://inlinedocs.r-forge.r-project.org/ but then I think it could be better to keep it at the GitHub link which is secure or https-marked, unless similar changes are made to inlinedocs landing page as well  -->
</tr>
<tr>
<td align="center">
    <a href="http://validator.w3.org/check?uri=referer">validate</a>
</td>
</tr>
</table>
</center>
```

**Comment by tdhock** [comment]
ElemStatLearn data sets can be downloaded from https://web.stanford.edu/~hastie/ElemStatLearn/data.html please copy them into directlabels package (or remove those examples if no longer relevant)

**Comment by Anirban166** [comment]
> ElemStatLearn data sets can be downloaded from https://web.stanford.edu/~hastie/ElemStatLearn/data.html please copy them into directlabels package (or remove those examples if no longer relevant)

Sorry for a late response, and thanks for that pointer!

In my initial attempt at resolving this, I had downloaded the entire repository from https://github.com/cran/ElemStatLearn/tree/master/data and placed it in my library (`/usr/local/lib/R/4.0/site-library/ElemStatLearn`) to make R load the required files, although it's not a valid installation (and the package can't be loaded, but the data can be accessed). This worked with `dldoc()`, but yes I could have just taken the `.Rdata` files from the repository and change instances of `data(x, package = "ElemStatLearn")` to simply `data(x)`. (I had the feeling that I would require the library since I guess back then you used the library directly via installing, when the package existed on Cran's active list, unlike its current orphaned state) I looked at the tests or corresponding [lineplot examples](http://directlabels.r-forge.r-project.org/docs/lineplot/posfuns/last.polygons.html), and figured that I require only `prostate.Rdata` (for `lars` and `ridge`), so I included that file in `directlabels/data` with the above changes and moved ahead of this problem. 

But apparently, these were just the core dependencies resolved (apart from `ggplot2` which was installed, there were two: `mlmrev` which got installed and loaded without any issues, and then the above resolved case for`ElemStatLearn`), because next came `lars`:
```r
> dldoc("/Users/anirban166/Downloads/directlabels")
Error in library(lars) : there is no package called ‘lars’
> install.packages("lars")
Installing package into ‘/usr/local/lib/R/4.0/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/lars_1.2.tgz'
Content type 'application/x-gzip' length 225827 bytes (220 KB)
==================================================
downloaded 220 KB


The downloaded binary packages are in
	/var/folders/4c/0p9lg83d5vq7cdwr7vw81_fc0000gn/T//Rtmp4TKE4o/downloaded_packages

> dldoc("/Users/anirban166/Downloads/directlabels")
Error: package or namespace load failed for ‘lars’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/4.0/site-library/lars/libs/lars.so':
  dlopen(/usr/local/lib/R/4.0/site-library/lars/libs/lars.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libgfortran.5.dylib
  Referenced from: /usr/local/lib/R/4.0/site-library/lars/libs/lars.so
  Reason: image not found
```
I tried to debug the error, and as far as I looked up on SO, it seems that the solution in most cases would be to re-install `x`, which is the concerned library unable to be loaded as per `Library not loaded: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/x.dylib` type messages. In this case the library was `libgfortran`, 
so I tried to search for that (it isn't a cran package clearly, I suppose its a 'default' library for compiling fortran code) everywhere. After a bit of futile search, I went to the GitHub repo for `gfortran` and from the list of different [MacOS releases](https://github.com/fxcoudert/gfortran-for-macOS/releases), I installed one for my [version](https://github.com/fxcoudert/gfortran-for-macOS/releases/tag/10.2). I wonder if they are the same, but since [Cran points](https://cran.r-project.org/bin/macosx/tools/) to this as well, I had hope. Sadly, that didn't work, even with the library path specified correctly. 

I didn't found anything via Homebrew as well: (all the libraries mentioned in the SO threads I came across pertaining to such issues had sources at Cran/GitHub, and often `brew update` would solve the case for some. But the first wasn't my case, and updating didn't help either)
```sh
anirban166$ brew install libgfortran
Updating Homebrew...
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "libgfortran".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

At this point, I thought to just skip past the example which required that, which would be the `lars` lineplot one. I deleted the file and tried to see if `dldoc()` would work now:
```r
> dldoc("/Users/anirban166/Downloads/directlabels")
Error in library(latticeExtra) : there is no package called ‘latticeExtra’
> install.packages("latticeExtra")
Installing package into ‘/usr/local/lib/R/4.0/site-library’
(as ‘lib’ is unspecified)
also installing the dependency ‘jpeg’

trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/jpeg_0.1-8.1.tgz'
Content type 'application/x-gzip' length 416504 bytes (406 KB)
==================================================
  downloaded 406 KB

trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/latticeExtra_0.6-29.tgz'
Content type 'application/x-gzip' length 2202360 bytes (2.1 MB)
==================================================
  downloaded 2.1 MB


The downloaded binary packages are in
/var/folders/4c/0p9lg83d5vq7cdwr7vw81_fc0000gn/T//Rtmp4TKE4o/downloaded_packages

> dldoc("/Users/anirban166/Downloads/directlabels")
Error: package or namespace load failed for ‘latticeExtra’ in dyn.load(file, DLLpath = DLLpath, ...):
  unable to load shared object '/usr/local/lib/R/4.0/site-library/jpeg/libs/jpeg.so':
  dlopen(/usr/local/lib/R/4.0/site-library/jpeg/libs/jpeg.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib
Referenced from: /usr/local/lib/R/4.0/site-library/jpeg/libs/jpeg.so
Reason: image not found
```
Exactly the same type of error, but for a different library, or in turn a different shared object unable to be loaded. I could have moved on from this as well by deleting/commenting-out `scatterplot/class-manufacturer.R` which required it, but this isn't what I'd want in the end and so I thought it would be best to remove RStudio along with the R packages installed, and to perform a fresh install, with everything installed from source. After installation, I cloned back my gh-pages repo, repeated the above steps, and this time, installing `lars` did the job, and I can finally load it now:
```r
> library(lars)
Loaded lars 1.2
```
But the happiness was short-lived, as what was worse was:
```r
> library(inlinedocs)
> library(directlabels)
> dldoc("/Users/anirban166/directlabels")
Loading required package: lattice
Error: package or namespace load failed for ‘ggplot2’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/4.0/site-library/colorspace/libs/colorspace.so':
  dlopen(/usr/local/lib/R/4.0/site-library/colorspace/libs/colorspace.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib
  Referenced from: /usr/local/lib/R/4.0/site-library/colorspace/libs/colorspace.so
  Reason: image not found
```
Previously `ggplot2` was working fine, but now I can't even load that. I tried installing it via source but that didn't work:
```r
> install.packages("ggplot2", type = "source")
Installing package into ‘/usr/local/lib/R/4.0/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/ggplot2_3.3.3.tar.gz'
Content type 'application/x-gzip' length 3058840 bytes (2.9 MB)
==================================================
downloaded 2.9 MB

* installing *source* package ‘ggplot2’ ...
** package ‘ggplot2’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (ggplot2)

The downloaded source packages are in
	‘/private/var/folders/4c/0p9lg83d5vq7cdwr7vw81_fc0000gn/T/Rtmphjarcu/downloaded_packages’
> library(ggplot2)
Error: package or namespace load failed for ‘ggplot2’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/4.0/site-library/colorspace/libs/colorspace.so':
  dlopen(/usr/local/lib/R/4.0/site-library/colorspace/libs/colorspace.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib
  Referenced from: /usr/local/lib/R/4.0/site-library/colorspace/libs/colorspace.so
  Reason: image not found
```

Since I'm facing such errors frequently, (also been having a lot of other issues lately) I'm thinking to switch to a development environment in Windows soon, given that these type of errors are known to specifically arise in MacOS.

**Comment by Anirban166** [comment]
> ElemStatLearn data sets can be downloaded from https://web.stanford.edu/~hastie/ElemStatLearn/data.html please copy them into directlabels package (or remove those examples if no longer relevant)

Sorry for a late response, and thanks for that pointer!

In my initial attempt at resolving this, I had downloaded the entire repository from https://github.com/cran/ElemStatLearn/tree/master/data and placed it in my library (`/usr/local/lib/R/4.0/site-library/ElemStatLearn`) to make R load the required files, although it's not a valid installation (and the package can't be loaded, but the data can be accessed). This worked with `dldoc()`, but yes I could have just taken the `.Rdata` files from the repository and change instances of `data(x, package = "ElemStatLearn")` to simply `data(x)`. (I had the feeling that I would require the library since I guess back then you used the library directly via installing, when the package existed on Cran's active list, unlike its current orphaned state) I looked at the tests or corresponding [lineplot examples](http://directlabels.r-forge.r-project.org/docs/lineplot/posfuns/last.polygons.html), and figured that I require only `prostate.Rdata` (for `lars` and `ridge`), so I included that file in `directlabels/data` with the above changes and moved ahead of this problem. 

But apparently, these were just the core dependencies resolved (apart from `ggplot2` which was installed, there were two: `mlmrev` which got installed and loaded without any issues, and then the above resolved case for`ElemStatLearn`), because next came `lars`:
```r
> dldoc("/Users/anirban166/Downloads/directlabels")
Error in library(lars) : there is no package called ‘lars’
> install.packages("lars")
Installing package into ‘/usr/local/lib/R/4.0/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/lars_1.2.tgz'
Content type 'application/x-gzip' length 225827 bytes (220 KB)
==================================================
downloaded 220 KB


The downloaded binary packages are in
	/var/folders/4c/0p9lg83d5vq7cdwr7vw81_fc0000gn/T//Rtmp4TKE4o/downloaded_packages

> dldoc("/Users/anirban166/Downloads/directlabels")
Error: package or namespace load failed for ‘lars’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/4.0/site-library/lars/libs/lars.so':
  dlopen(/usr/local/lib/R/4.0/site-library/lars/libs/lars.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libgfortran.5.dylib
  Referenced from: /usr/local/lib/R/4.0/site-library/lars/libs/lars.so
  Reason: image not found
```
I tried to debug the error, and as far as I looked up on SO, it seems that the solution in most cases would be to re-install `x`, which is the concerned library unable to be loaded as per `Library not loaded: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/x.dylib` type messages. In this case the library was `libgfortran`, 
so I tried to search for that (it isn't a cran package clearly, I suppose its a 'default' library for compiling fortran code) everywhere. After a bit of futile search, I went to the GitHub repo for `gfortran` and from the list of different [MacOS releases](https://github.com/fxcoudert/gfortran-for-macOS/releases), I installed one for my [version](https://github.com/fxcoudert/gfortran-for-macOS/releases/tag/10.2). I wonder if they are the same, but since [Cran points](https://cran.r-project.org/bin/macosx/tools/) to this as well, I had hope. Sadly, that didn't work, even with the library path specified correctly. 

I didn't find anything via Homebrew as well: (all the libraries mentioned in the SO threads I came across pertaining to such issues had sources at Cran/GitHub, and often `brew update` would solve the case for some. But the first wasn't my case, and updating didn't help either)
```sh
anirban166$ brew install libgfortran
Updating Homebrew...
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "libgfortran".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

At this point, I thought to just skip past the example which required that, which would be the `lars` lineplot one. I deleted the file and tried to see if `dldoc()` would work now:
```r
> dldoc("/Users/anirban166/Downloads/directlabels")
Error in library(latticeExtra) : there is no package called ‘latticeExtra’
> install.packages("latticeExtra")
Installing package into ‘/usr/local/lib/R/4.0/site-library’
(as ‘lib’ is unspecified)
also installing the dependency ‘jpeg’

trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/jpeg_0.1-8.1.tgz'
Content type 'application/x-gzip' length 416504 bytes (406 KB)
==================================================
  downloaded 406 KB

trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/latticeExtra_0.6-29.tgz'
Content type 'application/x-gzip' length 2202360 bytes (2.1 MB)
==================================================
  downloaded 2.1 MB


The downloaded binary packages are in
/var/folders/4c/0p9lg83d5vq7cdwr7vw81_fc0000gn/T//Rtmp4TKE4o/downloaded_packages

> dldoc("/Users/anirban166/Downloads/directlabels")
Error: package or namespace load failed for ‘latticeExtra’ in dyn.load(file, DLLpath = DLLpath, ...):
  unable to load shared object '/usr/local/lib/R/4.0/site-library/jpeg/libs/jpeg.so':
  dlopen(/usr/local/lib/R/4.0/site-library/jpeg/libs/jpeg.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib
Referenced from: /usr/local/lib/R/4.0/site-library/jpeg/libs/jpeg.so
Reason: image not found
```
Exactly the same type of error, but for a different library, or in turn a different shared object unable to be loaded. I could have moved on from this as well by deleting/commenting-out `scatterplot/class-manufacturer.R` which required it, but this isn't what I'd want in the end and so I thought it would be best to remove RStudio along with the R packages installed, and to perform a fresh install, with everything installed from source. After installation, I cloned back my gh-pages repo, repeated the above steps, and this time, installing `lars` did the job, and I can finally load it now:
```r
> library(lars)
Loaded lars 1.2
```
But the happiness was short-lived, as what was worse was:
```r
> library(inlinedocs)
> library(directlabels)
> dldoc("/Users/anirban166/directlabels")
Loading required package: lattice
Error: package or namespace load failed for ‘ggplot2’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/4.0/site-library/colorspace/libs/colorspace.so':
  dlopen(/usr/local/lib/R/4.0/site-library/colorspace/libs/colorspace.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib
  Referenced from: /usr/local/lib/R/4.0/site-library/colorspace/libs/colorspace.so
  Reason: image not found
```
Previously `ggplot2` was working fine, but now I can't even load that. I tried installing it via source but that didn't work:
```r
> install.packages("ggplot2", type = "source")
Installing package into ‘/usr/local/lib/R/4.0/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/ggplot2_3.3.3.tar.gz'
Content type 'application/x-gzip' length 3058840 bytes (2.9 MB)
==================================================
downloaded 2.9 MB

* installing *source* package ‘ggplot2’ ...
** package ‘ggplot2’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (ggplot2)

The downloaded source packages are in
	‘/private/var/folders/4c/0p9lg83d5vq7cdwr7vw81_fc0000gn/T/Rtmphjarcu/downloaded_packages’
> library(ggplot2)
Error: package or namespace load failed for ‘ggplot2’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/4.0/site-library/colorspace/libs/colorspace.so':
  dlopen(/usr/local/lib/R/4.0/site-library/colorspace/libs/colorspace.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib
  Referenced from: /usr/local/lib/R/4.0/site-library/colorspace/libs/colorspace.so
  Reason: image not found
```

Since I'm facing such errors frequently, (also been having a lot of other issues lately) I'm thinking to switch to a development environment in Windows soon, given that these type of errors are known to specifically arise in MacOS.

**Comment by tdhock** [comment]
I'm sorry I don't know how to fix that image not found problem, probably because I don't usually run R on mac. Did you try looking / asking on r-sig-mac? I found this thread which seems to be relevant, https://stat.ethz.ch/pipermail/r-sig-mac/2015-June/011514.html
It seems that the package so file is dynamically linked to the libR.dylib file -- did you try looking at ldd to see if the links are working? Does that libR.dylib file actually exist?

instead of windows, try installing ubuntu!

**Comment by Anirban166** [comment]
> Did you try looking / asking on r-sig-mac? 

No sorry I didn't ask there, but I had a look on similar threads after you mentioned this (I usually search on SO or whichever sites that pop up with relevant results from Googling!) but I didn't find a working answer

> I found this thread which seems to be relevant, https://stat.ethz.ch/pipermail/r-sig-mac/2015-June/011514.html

Yup that seems the same, but with regards to the end-solution in that thread, I did try `update.packages()` earlier  which had no effect

> It seems that the package so file is dynamically linked to the libR.dylib file -- did you try looking at ldd to see if the links are working? Does that libR.dylib file actually exist?

Your right! 
I tried to look for the file, but it doesn't exist:
```r
anirban166$ otool -L /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib
/Library/Developer/CommandLineTools/usr/bin/objdump: error: '/Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib': No such file or directory
```
![image](https://user-images.githubusercontent.com/30123691/112609561-ab20bd00-8e41-11eb-845e-851d96d032d9.png)

> instead of windows, try installing ubuntu!

I managed to install both, but the above errors were all resolved in Windows itself, so I'm currently using that 

There are a few more things to fix before getting `dldoc` to run, I'll include them in my application.
I suppose any *one* operating system would suffice for the runner that'll re-compute the docs and push the changes, so I'll definitely choose Ubuntu, but I can later try with MacOS if needed, just to see if these errors occur like they did for me. (for now we can completely ignore these since I'm no longer using OS X for local development, and so the above issues are non-existent)

**Comment by Anirban166** [comment]
Working well
![image](https://user-images.githubusercontent.com/30123691/112710295-f1c7f300-8ee5-11eb-830a-340ae3783bf0.png)
![image](https://user-images.githubusercontent.com/30123691/112710299-00160f00-8ee6-11eb-8d4f-f8590fc35944.png)

**Comment by Anirban166** [comment]
Working well, but wonder what those 'invalid parameters' signify?

![image](https://user-images.githubusercontent.com/30123691/112710295-f1c7f300-8ee5-11eb-830a-340ae3783bf0.png)
![image](https://user-images.githubusercontent.com/30123691/112710299-00160f00-8ee6-11eb-8d4f-f8590fc35944.png)
